# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4594ca7b3cce4f5dc9d3bbebd692009ebc351a2eab7e943283a69597c4933604f4d7883b07cb142fdb95d7992086ff3e5517e1b55c72f0345c7638904a9d439a

test:
  secret_key_base: 88c7764c69c121db685627bb2795c200df566b0c00184387b7db59594dfcbda6a7dd32ae5de48a245efad24542890ad85c276fee8b6d553eea1f91ff4a20070a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
